---
- name: setup smallstep ca systemd service
  become: true
  become_user: root
  block:
    - name: provide smallstep systemd service file
      copy:
        src: step-ca.service
        dest: /etc/systemd/system/step-ca.service
      tags: 
        - provide_smallstep_sysd_file
    - name: start smallstep ssl ca server
      systemd: 
        name: step-ca
        state: started
        enabled: yes
        daemon_reload: yes
      tags: 
        - start_smallstep_ssl_ca_server
    - name: wait for smallstep ssl ca server to start
      ansible.builtin.wait_for:
        timeout: 5
      tags: 
        - wait_for_smallstep_ssl_ca_server
